### ISSUE TITLE
Duplicate Filenames

### ISSUE THREAD

**Issue by falo2k** [ToofDerling/CbzMage#11]
Hi,

First up, love the utility.  Been a godsend for getting myself out of the horror of big A.

I've been running into some problems while converting a number of issues from Nightwing over various years.  While the Kindle app shows the titles with the series years (see screenshot), they're being named without any series year as filenames.  As a result, the app throws up errors about existing files because there's no distinction between the series.  

Could it potentially do something like use an incremental suffix on duplicate names if it happens, and then I can sort it out in comictagger afterwards?  Unfortunately, removing the already processed issues from the device and then reprocessing doesn't seem to then create the new titles.  i.e. if I had both 1995 and 2011 version of issue 1 downloaded in Kindle, run Azwconvert and get a complaint about duplicate filenames, check which has been created as a CBZ, move it elsewhere and then remove the kindle download, a future azwconvert doesn't try to get the other series' issue any more.

![image](https://user-images.githubusercontent.com/1392563/206523185-ca8bd2ff-0e33-4f32-87fd-f7af3e7a337a.png)

![image](https://user-images.githubusercontent.com/1392563/206523084-202fe31e-f58a-4dba-8edc-e07ad6c86c08.png)

**Comment by ToofDerling** [comment]
Thanks for the kind words, let's have a look at this.

I do believe CbzMage have access to the "extended title" with the series year (and sometimes other info), so I can likely fix the bug by simply using that (instead of the short version). I'll have a look.

As far as I can tell your workaround should be working. Have you deleted the title you're trying to "reconvert" from the converted titles folder?

**Comment by falo2k** [comment]
Yeah, removed at both target converted file and the kindle download.  No major issue - I'll find the gaps when I get it all into mylar.  Give me a nudge if you do a change and I can test it again.

**Comment by ToofDerling** [comment]
v0.15 is up with the fix.

**Comment by falo2k** [comment]
Seems to still have issues - not reprocessed the Nightwing ones again yet, but a similar problem crops up with Superboy (2010-2011) vs Superboy (2011-2014).  As you can see, in Kindle they do have distinct titles, but it failed with a collision on Superboy #6.  Could it be that the Amazon metadata is just trash (given the presence of "Sueprboy 30") and I'll have to just d/l the series individually with the titles cleared in between?

![image](https://user-images.githubusercontent.com/1392563/206587354-ba3b8793-e0e6-4602-b27a-1bf4c5c5042e.png)

![image](https://user-images.githubusercontent.com/1392563/206587302-a991d6fa-691c-4536-a150-b0dca787e642.png)

![image](https://user-images.githubusercontent.com/1392563/206586992-851d2123-9049-4f59-a7bb-382c0d0b46e6.png)

**Comment by falo2k** [comment]
Sorry, forgot to add, in this case the Superboy #6 that has been downloaded with no years is the issue from the (2010-2011) series so it doesn't appear to name consistently with the other (2010-2011) downloads.

**Comment by ToofDerling** [comment]
I'm fairly certain that we're getting the correct metadata now (ie: what you're seeing in Kdl). 

You're still having issues because once CbzMage reads the metadata from a book it saves the title and uses the saved title from then on (unless you change it manually). 

I think you need to start from scratch and let CbzMage regenerate the title files. So, delete the Titles folder (including Converted Titles and archive.db) and let it reconvert everything. Sorry about that.

**Comment by falo2k** [comment]
Add to KDL, then run AzwConvert (then comictagger, etc.).  I'll clear down my Titles folder later and give it another shot.  Am almost at the end of project "get my books back in a decent format".

**Comment by ToofDerling** [comment]
Try v0.16 that "fixex the fix" from the last version. If you still get duplicate filenames I'll do what you initially suggested: create some sort of suffix that makes filenames unique.

**Comment by falo2k** [comment]
Cleaned out Titles and installed 0.16 and all is well - tested against a few different series of common names.  Neatly named files, all with year/volume distinctions, and as an added bonus Superboy #30 is now spelt correctly ;)

Many thanks for your quick work!

**Comment by ToofDerling** [comment]
Excellent. Glad it's fixed for you.
