### ISSUE TITLE
Error on CompressionLevel=None

### ISSUE THREAD

**Issue by saltmanz** [ToofDerling/CbzMage#2]
If I try setting CompressionLevel to "None", I get an error:

CbzMage error:: InvalidOperationException: Failed to convert configuration value at 'CompressionLevel' to type 'System.IO.Compression.CompressionLevel'.

**Comment by ToofDerling** [comment]
Thank you for my very first bug report :)

That's a typo in the appsetting.json documentation. The correct parameter is "NoCompression". I'll update the release.
