### ISSUE TITLE
Not enough memory resources are available to process this command

### ISSUE THREAD

**Issue by saltmanz** [ToofDerling/CbzMage#5]
I'm slowly working on converting a couple thousand comics. I just downloaded maybe 30-40 and ran convert, and it processed maybe a dozen before popping up this error:

> CbzMage error:: AggregateException: One or more errors occurred. (Not enough memory resources are available to process this command.)

The last comic listed seemed to have generated fine, so I tried running a convert again, and this time the error reappeared after maybe 5 conversions. I ran a few more conversions, each time getting the error after 5-7 books. But I was able to successfully convert everything, so maybe it was a certain pagecount threshold? I'm kind of hoping at some point I can just let this run for an hour at a time or something.

**Comment by ToofDerling** [comment]
Try v0.4 which I just published. It targets x64 so it can use all the memory it may need.

How much memory do you have in your computer? And did you change the NumberOfThreads setting?

**Comment by saltmanz** [comment]
16GB of memory. I didn't touch the thread count.

New version seems to fix it, though; I just converted 54 comics at once (5399 pages) without a problem.

**Comment by ToofDerling** [comment]
16 Gb is more than enough. Good that it works now, dunno why I didn't target x64 from the beginning. But that's why it's a 0.x release, to get these kind of problems solved.
