### ISSUE TITLE
IOException: The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by saltmanz** [ToofDerling/CbzMage#7]
> CbzMage error:: IOException: The filename, directory name, or volume label syntax is incorrect. : 'C:\CbzMage\\_Titles\\[Marvel] Young Avengers Vol. 1 Style > Substance'

I assume it's the greater-than symbol in the comic title that's causing the issue. This one's a game-breaker, too; as long as that comic is downloaded, neither convert nor scan will run properly. (They all immediately give the error.)

**Comment by ToofDerling** [comment]
Yeah, that's definitely an illegal filename on Windows. I just verified that it's impossible to create a file with that name. Are you running CbzMage through Wine or something like that?

Anyway, there's some code that should make sure invalid file character are removed, but it's checking things in the wrong order. I'll have a fix up very soon. For now you can simply rename the file and remove the ">" that should make things run again.

**Comment by ToofDerling** [comment]
v0.5 is up with the fix, though you still need to rename that file to nudge it along. Also I'm not sure you won't run into the problem again if you are running on Wine. But a rename should always fix the issue.

**Comment by ToofDerling** [comment]
I just realized that the error may be before any file is written which actually makes more sense. In that case the fix should work and you'll end up with a title file named "[Marvel] Young Avengers Vol. 1 Style Substance"

**Comment by ToofDerling** [comment]
Leaving this open for now.

**Comment by saltmanz** [comment]
Right, that was the problem (or so it seemed to me): the program itself was trying to generate a filename with the invalid characters, which caused the error. I'll give the new version a shot in a bit.

**Comment by saltmanz** [comment]
No longer an issue in version 0.6.
