### ISSUE TITLE
Updated files found over and over again

### ISSUE THREAD

**Issue by saltmanz** [ToofDerling/CbzMage#8]
Not quite sure how to title this. I ran out of room on my C drive, so I relocated my Kindle Books folder to my D drive. I left the already-downloaded files intact, and changed the Kindle app and CbzMage to point to the new D drive location. I was hoping that by leaving the files intact, the Kindle app would recognize them as already downloaded. No, instead it's forcing me to redownload everything. Fine, I can live with that.

The real problem, however, is that after I download a bunch of books (new and old, I can't tell as I'm downloading them) and then run CbzMage, your program sees the redownloaded books as newly updated, and has to parse through all of them. Not so bad, except that it never stops seeing them as updated. For example I downloaded a bunch last night, then ran CbzMage. It said something like (made up numbers as an example): 188 updated books found, 41 unconverted. It reads the 188, then converts the 41. So far, so good. But when I immediately ran CbzMage again, it said 188 updated books found, 0 unconverted. It's somehow failing to note that it already checked the redownloaded books for updates.

**Comment by ToofDerling** [comment]
I think the "updated" mechanism is working as it should, but it not designed very well. Let's find out - are you seeing something similar to this every time you start CbzMage:

Found 1 updated book
Found 0 unconverted books

Scanning 1 updated book for changes:

1/1 - [Marvel] Black Widow Vol. 3 Die By The Blade

Done

**Comment by saltmanz** [comment]
Essentially yes, though at this point it's many hundreds of "updated" books that it finds and scans every time. And if I were to run CbzMage 3 times in a row, it would give me the same list of updated books all 3 times.

**Comment by ToofDerling** [comment]
Alright. I'll put on my thinking cap and figure something out. Besides slowing down CbzMage at startup it's not doing any harm, so you can ignore it for now (though it's obviously annoying and should be fixed).

**Comment by ToofDerling** [comment]
By the way, to keep your downloads when moving the Kdl content directory you need to move everything from the old directory into the new. I added a Wiki entry describing this: https://github.com/ToofDerling/CbzMage/wiki/How-to-move-Kdl-content-folder.

**Comment by saltmanz** [comment]
> By the way, to keep your downloads when moving the Kdl content directory you need to move everything from the old directory into the new. I added a Wiki entry describing [this:](https://github.com/ToofDerling/CbzMage/wiki/How-to-move-Kdl-content-folder.)

Ah, I see my mistake was copying everything first and then changing my settings in the Kindle app. (I still may be able to recover most of it by pulling the old db out of the recycle bin.)

**Comment by ToofDerling** [comment]
v0.12 is up with a fix for this issue. You'll see the list of updated books once more, then it won't happen again (unless the books are updated again).

Hope you get your books back. Redownloading is a pain.

**Comment by ToofDerling** [comment]
Can we close this?

**Comment by saltmanz** [comment]
Yep, hadn't gotten a chance to test it out before now. Downloaded the new version and ran it; it scanned all 312 books again. Ran it again, it found 0 updates and finished immediately.

**Comment by ToofDerling** [comment]
Excellent, thanks for testing.
